### ISSUE TITLE
Cythonize thermal model

### ISSUE THREAD

**Issue by JeisonPacateque** [JeisonPacateque/Proyecto-de-Grado-Codes#5]
In order to speed up the simulation, it is desirable to use cython to calculate Laplacian

**Comment by hibikimsp** [comment]
Not a proirity now, but i agree

**Comment by hibikimsp** [comment]
After running the thermal simulation over a Core i5 3337U@Wintendows 7 (Python 2.7 on a usb...) 

Thermal simulation done in  2.22699999809  seconds. 100 steps
Thermal simulation done in  23.5509998798  seconds. 1000 steps
Thermal simulation done in  223.221999884  seconds. 10000 steps

Pretty consistent ;)

I don't think cython wrap its needed for release

**Comment by JeisonPacateque** [comment]
We

**Comment by hibikimsp** [comment]
Still not enough argument to "cythonice"

**Comment by JeisonPacateque** [comment]
Fist attempt donde and functional

**Comment by JeisonPacateque** [comment]
No es creyente, llave
